project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd    
    - project.qmd
  
website:
  title: ""
  search: false

  navbar:
    title: BUSI 722
    link-external-newwindow: true
    search: false
    right:   

      - text: Group Project
        file: project.qmd

      - text: Code Binder
        href: https://mybinder.org/v2/gh/kerryback/2023-722-binder.git/HEAD

      - text: Slide Decks
        file: slides.qmd

      - text: Home
        file: index.qmd

format: 
  html:
    theme: cosmo
    scss: styles.css
    link-external-newwindow: true
      



